language: c

sudo: false

addons:
  apt:
    packages:
    - libgmp-dev

cache:
  directories:
    - $HOME/.stack
    - .stack-work

before_install:
  - mkdir -pv ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH

install:
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script:
  - stack --no-terminal --install-ghc test --flag scale:dev
  - stack --no-terminal sdist
  - stack --no-terminal haddock --no-haddock-deps

notifications:
  email: false
